### ISSUE TITLE
求全部答案

### ISSUE THREAD

**Issue by ricklessboy** [liuzengh/combinatorial-mathematics#1]
请问能不能也给一下第一章鸽巢原理的答案呢，非常感谢

**Comment by liuzengh** [comment]
如果我有对应的答案的话，是非常乐意提供的。 但是，自从学校毕业之后，就没有相关记录保存其他章节的答案了。

目前自己从事软件开发工作，日常使用到组合数学的知识非常少，暂时没有意愿和时间维护该项目。 望谅解。
